spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
    show-sql: false
  flyway:
    enabled: false
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/wcp;AUTO_SERVER=TRUE
    username: sa
    password: 