spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: true
  flyway:
    enabled: false
server:
  port: 8081
---
spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/.h2/wcp;AUTO_SERVER=TRUE
    username: sa
    password:
  jpa:
    show-sql: true
  dubbo:
    registry: zookeeper://localhost:2181
  security:
    user:
      name: user
      password: user
      roles: ADMIN