spring:
  application:
    name: @project.artifactId@
  profiles:
    active: qa

server:
  port: 9091

mybatis:
  type-aliases-package: com.midea.wcp.user.mybatis.model

wcp:


---
spring:
  profiles: dev
  dubbo:
    registry: zookeeper://localhost:2181
---
spring:
  profiles: qa
#  dubbo:
#    registry: zookeeper://10.16.25.121:2182
  rabbitmq:
    host: 10.16.41.230
    username: admin
    password: admin
    port: 5672
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.16.18.182:3306/wcp_beta?userUnicode=true&characterEncoding=utf-8&allowMultiQueries=true
    username: wx_user
    password: Weixin12389