spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
server:
  port: 9091
---
spring:
  profiles: dev
  dubbo:
    registry: zookeeper://localhost:2181
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    template:
      queue: wcp-sync-user
---
spring:
  profiles: qa
  dubbo:
    registry: zookeeper://10.16.25.121:2182
  rabbitmq:
    host: 10.16.41.230
    username: admin
    password: admin
    port: 5672