spring:
  application:
    name: @project.artifactId@
  profiles:
    active: dev
server:
  port: 8081
---
spring:
  profiles: dev
  dubbo:
    registry: zookeeper://localhost:2181
---
spring:
  profiles: qa
  dubbo:
    registry: zookeeper://10.16.25.121:2181
